// Standard UAE construction & prefab manufacturing chart of accounts.
// 130+ accounts covering Assets, Liabilities, Equity, Revenue, Cost of Sales, and Operating Expenses.
// Codes follow industry convention: 1xxx Assets, 2xxx Liabilities, 3xxx Equity, 4xxx Income,
// 5xxx Cost of Sales / Direct Costs, 6xxx Operating & Admin Expenses.

export interface CoaSeed {
  accountCode: string;
  accountName: string;
  accountType: string;
  description?: string;
}

export const CONSTRUCTION_COA_TEMPLATE: CoaSeed[] = [
  // ───────────────────────────────────── 1xxx ASSETS ─────────────────────────────────────
  { accountCode: "1100", accountName: "Cash on Hand", accountType: "Cash" },
  { accountCode: "1110", accountName: "Petty Cash", accountType: "Cash" },
  { accountCode: "1200", accountName: "Bank - Current Account (AED)", accountType: "Bank" },
  { accountCode: "1210", accountName: "Bank - Savings Account", accountType: "Bank" },
  { accountCode: "1220", accountName: "Bank - USD Account", accountType: "Bank" },
  { accountCode: "1230", accountName: "Bank - Project Escrow", accountType: "Bank" },
  { accountCode: "1300", accountName: "Accounts Receivable - Trade", accountType: "Assets" },
  { accountCode: "1310", accountName: "Accounts Receivable - Retention", accountType: "Assets" },
  { accountCode: "1320", accountName: "Accounts Receivable - Related Parties", accountType: "Assets" },
  { accountCode: "1330", accountName: "Allowance for Doubtful Debts", accountType: "Assets" },
  { accountCode: "1400", accountName: "Advance to Suppliers", accountType: "Assets" },
  { accountCode: "1410", accountName: "Prepaid Expenses", accountType: "Assets" },
  { accountCode: "1420", accountName: "Prepaid Insurance", accountType: "Assets" },
  { accountCode: "1430", accountName: "Prepaid Rent", accountType: "Assets" },
  { accountCode: "1440", accountName: "Refundable Deposits (Utilities)", accountType: "Assets" },
  { accountCode: "1500", accountName: "Inventory - Raw Materials (Steel/MS)", accountType: "Assets" },
  { accountCode: "1510", accountName: "Inventory - Sandwich Panels", accountType: "Assets" },
  { accountCode: "1520", accountName: "Inventory - Cement Board", accountType: "Assets" },
  { accountCode: "1530", accountName: "Inventory - Aluminum Composite Panels", accountType: "Assets" },
  { accountCode: "1540", accountName: "Inventory - Insulation (Rock-wool/EPS)", accountType: "Assets" },
  { accountCode: "1550", accountName: "Inventory - Hardware & Fasteners", accountType: "Assets" },
  { accountCode: "1560", accountName: "Inventory - Electrical Components", accountType: "Assets" },
  { accountCode: "1570", accountName: "Inventory - Plumbing Materials", accountType: "Assets" },
  { accountCode: "1580", accountName: "Inventory - Paints & Chemicals", accountType: "Assets" },
  { accountCode: "1590", accountName: "Work-in-Progress (WIP)", accountType: "Assets" },
  { accountCode: "1600", accountName: "Finished Cabins / Stock", accountType: "Assets" },
  { accountCode: "1700", accountName: "VAT Input Receivable", accountType: "VAT Input" },
  { accountCode: "1710", accountName: "Recoverable VAT - Imports", accountType: "VAT Input" },
  { accountCode: "1800", accountName: "Land", accountType: "Assets" },
  { accountCode: "1810", accountName: "Buildings & Factory", accountType: "Assets" },
  { accountCode: "1820", accountName: "Plant & Machinery", accountType: "Assets" },
  { accountCode: "1830", accountName: "Tools & Small Equipment", accountType: "Assets" },
  { accountCode: "1840", accountName: "Office Equipment", accountType: "Assets" },
  { accountCode: "1850", accountName: "Computers & IT Equipment", accountType: "Assets" },
  { accountCode: "1860", accountName: "Furniture & Fixtures", accountType: "Assets" },
  { accountCode: "1870", accountName: "Vehicles - Heavy (Trucks/Trailers)", accountType: "Assets" },
  { accountCode: "1880", accountName: "Vehicles - Light (Cars/Pickups)", accountType: "Assets" },
  { accountCode: "1890", accountName: "Cranes & Lifting Equipment", accountType: "Assets" },
  { accountCode: "1900", accountName: "Welding Machines", accountType: "Assets" },
  { accountCode: "1910", accountName: "Capital Work in Progress (CWIP)", accountType: "Assets" },
  { accountCode: "1920", accountName: "Accumulated Depreciation - Buildings", accountType: "Assets" },
  { accountCode: "1930", accountName: "Accumulated Depreciation - Plant & Machinery", accountType: "Assets" },
  { accountCode: "1940", accountName: "Accumulated Depreciation - Vehicles", accountType: "Assets" },
  { accountCode: "1950", accountName: "Accumulated Depreciation - Office Equipment", accountType: "Assets" },

  // ───────────────────────────────────── 2xxx LIABILITIES ─────────────────────────────────────
  { accountCode: "2100", accountName: "Accounts Payable - Trade", accountType: "Liabilities" },
  { accountCode: "2110", accountName: "Accounts Payable - Subcontractors", accountType: "Liabilities" },
  { accountCode: "2120", accountName: "Accounts Payable - Related Parties", accountType: "Liabilities" },
  { accountCode: "2200", accountName: "Accrued Expenses", accountType: "Liabilities" },
  { accountCode: "2210", accountName: "Accrued Wages & Salaries", accountType: "Liabilities" },
  { accountCode: "2220", accountName: "Accrued Utilities", accountType: "Liabilities" },
  { accountCode: "2230", accountName: "Accrued Subcontractor Costs", accountType: "Liabilities" },
  { accountCode: "2300", accountName: "Customer Advances Received", accountType: "Liabilities" },
  { accountCode: "2310", accountName: "Retention Payable to Subcontractors", accountType: "Liabilities" },
  { accountCode: "2320", accountName: "Mobilization Advance Received", accountType: "Liabilities" },
  { accountCode: "2400", accountName: "VAT Output Payable", accountType: "VAT Output" },
  { accountCode: "2410", accountName: "VAT Payable to FTA (net)", accountType: "VAT Output" },
  { accountCode: "2500", accountName: "End of Service Benefits Payable (EOSB)", accountType: "Liabilities" },
  { accountCode: "2510", accountName: "Salaries & Wages Payable", accountType: "Liabilities" },
  { accountCode: "2520", accountName: "Leave Salary Payable", accountType: "Liabilities" },
  { accountCode: "2530", accountName: "Air Ticket Provision", accountType: "Liabilities" },
  { accountCode: "2540", accountName: "Bonus Payable", accountType: "Liabilities" },
  { accountCode: "2600", accountName: "Bank Overdraft", accountType: "Liabilities" },
  { accountCode: "2610", accountName: "Short-term Bank Loans", accountType: "Liabilities" },
  { accountCode: "2620", accountName: "Long-term Bank Loans", accountType: "Liabilities" },
  { accountCode: "2630", accountName: "Vehicle Loans", accountType: "Liabilities" },
  { accountCode: "2640", accountName: "Equipment Finance Lease", accountType: "Liabilities" },
  { accountCode: "2700", accountName: "Corporate Income Tax Payable", accountType: "Liabilities" },
  { accountCode: "2800", accountName: "Provision for Warranties", accountType: "Liabilities" },

  // ───────────────────────────────────── 3xxx EQUITY ─────────────────────────────────────
  { accountCode: "3100", accountName: "Share Capital", accountType: "Equity" },
  { accountCode: "3200", accountName: "Partner Current Accounts", accountType: "Equity" },
  { accountCode: "3300", accountName: "Retained Earnings", accountType: "Equity" },
  { accountCode: "3400", accountName: "Current Year Profit / Loss", accountType: "Equity" },
  { accountCode: "3500", accountName: "Owner Drawings", accountType: "Equity" },

  // ───────────────────────────────────── 4xxx INCOME / REVENUE ─────────────────────────────────────
  { accountCode: "4100", accountName: "Revenue - Standard Prefab Cabin Sales", accountType: "Income" },
  { accountCode: "4110", accountName: "Revenue - Modified Container Sales", accountType: "Income" },
  { accountCode: "4120", accountName: "Revenue - Sandwich Panel Cabin Sales", accountType: "Income" },
  { accountCode: "4130", accountName: "Revenue - Aluminum Cladding Cabin Sales", accountType: "Income" },
  { accountCode: "4140", accountName: "Revenue - Custom / Bespoke Projects", accountType: "Income" },
  { accountCode: "4200", accountName: "Revenue - Installation Services", accountType: "Income" },
  { accountCode: "4210", accountName: "Revenue - Site Preparation Services", accountType: "Income" },
  { accountCode: "4220", accountName: "Revenue - Maintenance & AMC", accountType: "Income" },
  { accountCode: "4230", accountName: "Revenue - Refurbishment Services", accountType: "Income" },
  { accountCode: "4240", accountName: "Revenue - Cabin Rental Income", accountType: "Income" },
  { accountCode: "4300", accountName: "Revenue - Subcontracting Income", accountType: "Income" },
  { accountCode: "4400", accountName: "Revenue - Spare Parts & Accessories", accountType: "Income" },
  { accountCode: "4500", accountName: "Other Operating Income", accountType: "Income" },
  { accountCode: "4510", accountName: "Scrap Sales", accountType: "Income" },
  { accountCode: "4520", accountName: "Foreign Exchange Gain", accountType: "Income" },
  { accountCode: "4530", accountName: "Discount Received", accountType: "Income" },
  { accountCode: "4540", accountName: "Interest Income", accountType: "Income" },

  // ───────────────────────────────────── 5xxx COST OF SALES / DIRECT COSTS ─────────────────────────────────────
  { accountCode: "5100", accountName: "Direct Materials - Steel & MS Sections", accountType: "Cost of Goods Sold" },
  { accountCode: "5110", accountName: "Direct Materials - Sandwich Panels", accountType: "Cost of Goods Sold" },
  { accountCode: "5120", accountName: "Direct Materials - Cement Board", accountType: "Cost of Goods Sold" },
  { accountCode: "5130", accountName: "Direct Materials - ACP Cladding", accountType: "Cost of Goods Sold" },
  { accountCode: "5140", accountName: "Direct Materials - Insulation", accountType: "Cost of Goods Sold" },
  { accountCode: "5150", accountName: "Direct Materials - Doors & Windows", accountType: "Cost of Goods Sold" },
  { accountCode: "5160", accountName: "Direct Materials - Electrical", accountType: "Cost of Goods Sold" },
  { accountCode: "5170", accountName: "Direct Materials - Plumbing", accountType: "Cost of Goods Sold" },
  { accountCode: "5180", accountName: "Direct Materials - Paints & Coatings", accountType: "Cost of Goods Sold" },
  { accountCode: "5190", accountName: "Direct Materials - Hardware & Consumables", accountType: "Cost of Goods Sold" },
  { accountCode: "5200", accountName: "Direct Labor - Welders", accountType: "Cost of Goods Sold" },
  { accountCode: "5210", accountName: "Direct Labor - Carpenters", accountType: "Cost of Goods Sold" },
  { accountCode: "5220", accountName: "Direct Labor - Electricians", accountType: "Cost of Goods Sold" },
  { accountCode: "5230", accountName: "Direct Labor - Plumbers", accountType: "Cost of Goods Sold" },
  { accountCode: "5240", accountName: "Direct Labor - Painters", accountType: "Cost of Goods Sold" },
  { accountCode: "5250", accountName: "Direct Labor - Helpers / Unskilled", accountType: "Cost of Goods Sold" },
  { accountCode: "5260", accountName: "Direct Labor - Site Supervisors", accountType: "Cost of Goods Sold" },
  { accountCode: "5300", accountName: "Subcontractor - Civil Works", accountType: "Cost of Goods Sold" },
  { accountCode: "5310", accountName: "Subcontractor - MEP", accountType: "Cost of Goods Sold" },
  { accountCode: "5320", accountName: "Subcontractor - Foundation", accountType: "Cost of Goods Sold" },
  { accountCode: "5330", accountName: "Subcontractor - Site Installation", accountType: "Cost of Goods Sold" },
  { accountCode: "5340", accountName: "Subcontractor - Crane Hire", accountType: "Cost of Goods Sold" },
  { accountCode: "5400", accountName: "Site Mobilization Costs", accountType: "Cost of Goods Sold" },
  { accountCode: "5410", accountName: "Transportation - Cabin Delivery", accountType: "Cost of Goods Sold" },
  { accountCode: "5420", accountName: "Loading & Offloading Charges", accountType: "Cost of Goods Sold" },
  { accountCode: "5430", accountName: "Site Travel & Accommodation", accountType: "Cost of Goods Sold" },
  { accountCode: "5500", accountName: "Plant & Equipment Hire (Production)", accountType: "Cost of Goods Sold" },
  { accountCode: "5510", accountName: "Tools & Consumables (Workshop)", accountType: "Cost of Goods Sold" },
  { accountCode: "5520", accountName: "Welding Gas & Electrodes", accountType: "Cost of Goods Sold" },
  { accountCode: "5530", accountName: "Power & Fuel - Site / Workshop", accountType: "Cost of Goods Sold" },
  { accountCode: "5540", accountName: "Site Office Setup Costs", accountType: "Cost of Goods Sold" },
  { accountCode: "5600", accountName: "Quality Control & Testing", accountType: "Cost of Goods Sold" },
  { accountCode: "5610", accountName: "Third Party Inspection Fees", accountType: "Cost of Goods Sold" },
  { accountCode: "5620", accountName: "Manufacturing Waste & Rework", accountType: "Cost of Goods Sold" },
  { accountCode: "5700", accountName: "Factory Rent", accountType: "Cost of Goods Sold" },
  { accountCode: "5710", accountName: "Factory Utilities (DEWA/SEWA)", accountType: "Cost of Goods Sold" },
  { accountCode: "5720", accountName: "Factory Maintenance & Repairs", accountType: "Cost of Goods Sold" },

  // ───────────────────────────────────── 6xxx OPERATING & ADMIN EXPENSES ─────────────────────────────────────
  { accountCode: "6100", accountName: "Salaries - Office Staff", accountType: "Expenses" },
  { accountCode: "6110", accountName: "Salaries - Sales Team", accountType: "Expenses" },
  { accountCode: "6120", accountName: "Salaries - Engineering & Design", accountType: "Expenses" },
  { accountCode: "6130", accountName: "Salaries - Project Management", accountType: "Expenses" },
  { accountCode: "6140", accountName: "Staff Commissions & Bonuses", accountType: "Expenses" },
  { accountCode: "6150", accountName: "Staff Allowances (Housing/Transport)", accountType: "Expenses" },
  { accountCode: "6160", accountName: "Visa & Labor Card Renewal", accountType: "Expenses" },
  { accountCode: "6170", accountName: "Medical Insurance - Staff", accountType: "Expenses" },
  { accountCode: "6180", accountName: "EOSB Provision Expense", accountType: "Expenses" },
  { accountCode: "6190", accountName: "Training & Development", accountType: "Expenses" },
  { accountCode: "6200", accountName: "Office Rent", accountType: "Expenses" },
  { accountCode: "6210", accountName: "Office Utilities", accountType: "Expenses" },
  { accountCode: "6220", accountName: "Telephone & Internet", accountType: "Expenses" },
  { accountCode: "6230", accountName: "Office Maintenance & Cleaning", accountType: "Expenses" },
  { accountCode: "6240", accountName: "Office Supplies & Stationery", accountType: "Expenses" },
  { accountCode: "6250", accountName: "Printing & Copying", accountType: "Expenses" },
  { accountCode: "6300", accountName: "Marketing & Advertising", accountType: "Expenses" },
  { accountCode: "6310", accountName: "Website & Digital Marketing", accountType: "Expenses" },
  { accountCode: "6320", accountName: "Trade Show / Exhibition Costs", accountType: "Expenses" },
  { accountCode: "6330", accountName: "Brochures & Sales Material", accountType: "Expenses" },
  { accountCode: "6400", accountName: "Travel & Conveyance", accountType: "Expenses" },
  { accountCode: "6410", accountName: "Vehicle Fuel - Office", accountType: "Expenses" },
  { accountCode: "6420", accountName: "Vehicle Maintenance - Office", accountType: "Expenses" },
  { accountCode: "6430", accountName: "Vehicle Insurance", accountType: "Expenses" },
  { accountCode: "6440", accountName: "Salik / Toll Charges", accountType: "Expenses" },
  { accountCode: "6450", accountName: "Vehicle Registration & Renewal", accountType: "Expenses" },
  { accountCode: "6500", accountName: "Insurance - Workmen Compensation", accountType: "Expenses" },
  { accountCode: "6510", accountName: "Insurance - Public Liability", accountType: "Expenses" },
  { accountCode: "6520", accountName: "Insurance - Property", accountType: "Expenses" },
  { accountCode: "6530", accountName: "Insurance - Marine / Transit", accountType: "Expenses" },
  { accountCode: "6600", accountName: "Professional Fees - Legal", accountType: "Expenses" },
  { accountCode: "6610", accountName: "Professional Fees - Audit & Accounting", accountType: "Expenses" },
  { accountCode: "6620", accountName: "Professional Fees - Tax Consulting", accountType: "Expenses" },
  { accountCode: "6630", accountName: "Professional Fees - Engineering Consultants", accountType: "Expenses" },
  { accountCode: "6640", accountName: "Bank Charges", accountType: "Expenses" },
  { accountCode: "6650", accountName: "Credit Card / POS Charges", accountType: "Expenses" },
  { accountCode: "6660", accountName: "Foreign Exchange Loss", accountType: "Expenses" },
  { accountCode: "6700", accountName: "Trade License & Permits", accountType: "Expenses" },
  { accountCode: "6710", accountName: "Tejari / Bidding Platform Fees", accountType: "Expenses" },
  { accountCode: "6720", accountName: "Municipality / Civil Defense Fees", accountType: "Expenses" },
  { accountCode: "6730", accountName: "Authority Approvals & Inspections", accountType: "Expenses" },
  { accountCode: "6740", accountName: "Chamber of Commerce Fees", accountType: "Expenses" },
  { accountCode: "6750", accountName: "Membership / Subscription Fees", accountType: "Expenses" },
  { accountCode: "6800", accountName: "Depreciation - Buildings", accountType: "Expenses" },
  { accountCode: "6810", accountName: "Depreciation - Plant & Machinery", accountType: "Expenses" },
  { accountCode: "6820", accountName: "Depreciation - Vehicles", accountType: "Expenses" },
  { accountCode: "6830", accountName: "Depreciation - Office Equipment", accountType: "Expenses" },
  { accountCode: "6840", accountName: "Depreciation - Furniture & Fixtures", accountType: "Expenses" },
  { accountCode: "6850", accountName: "Depreciation - IT Equipment", accountType: "Expenses" },
  { accountCode: "6900", accountName: "Bad Debts Written Off", accountType: "Expenses" },
  { accountCode: "6910", accountName: "Provision for Doubtful Debts", accountType: "Expenses" },
  { accountCode: "6920", accountName: "Donations & Charity", accountType: "Expenses" },
  { accountCode: "6930", accountName: "Sponsorships", accountType: "Expenses" },
  { accountCode: "6940", accountName: "Penalties & Fines", accountType: "Expenses" },
  { accountCode: "6950", accountName: "Miscellaneous Expenses", accountType: "Expenses" },
  { accountCode: "6960", accountName: "Interest Expense - Bank Loans", accountType: "Expenses" },
  { accountCode: "6970", accountName: "Interest Expense - Equipment Finance", accountType: "Expenses" },
];

export const CONSTRUCTION_COA_COUNT = CONSTRUCTION_COA_TEMPLATE.length;
